[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
voicevox_api = { git = "https://github.com/mkanenobu/voicevox-api-rust" }
tokio = { version = "1.27", features = ["full"] }