/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SpeakerSupportPermittedSynthesisMorphing : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpeakerSupportPermittedSynthesisMorphing {
    #[serde(rename = "ALL")]
    All,
    #[serde(rename = "SELF_ONLY")]
    SelfOnly,
    #[serde(rename = "NOTHING")]
    Nothing,

}

impl ToString for SpeakerSupportPermittedSynthesisMorphing {
    fn to_string(&self) -> String {
        match self {
            Self::All => String::from("ALL"),
            Self::SelfOnly => String::from("SELF_ONLY"),
            Self::Nothing => String::from("NOTHING"),
        }
    }
}

impl Default for SpeakerSupportPermittedSynthesisMorphing {
    fn default() -> SpeakerSupportPermittedSynthesisMorphing {
        Self::All
    }
}




